### PR TITLE
Data file for vector<DetId> unit test.

### PR DESCRIPTION
**Pull request by wddgit**
Add initial data file for ```std::vector<DetId>``` unit test.

### CODE REVIEW

**Comment by wddgit** [comment]
please test

FYI @makortel.

This PR test does nothing, but I'm running it to check the box. The new unit test in PR cms-sw/cmssw#42877 will be the only that tests this PR. That unit test reads the input file added by this PR.

**Comment by rappoccio** [comment]
+1

**Comment by rappoccio** [comment]
merge

* CMSSW PR is already signed, forcing merge.

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
